@startuml
title Smart-Parking-Lot
footer Page %page% of %lastpage%

actor USER as user
actor Administrator as admin
control Server as server
entity MainCam as main
entity EntranceCam as enter
entity JunctionSign as sign

main->main : 프로그램 시작
activate main #blue
main -> main : 차량 디텍팅 루프
==입차 관리==
enter -> enter : [START] 차량 인식
activate enter
    group 차량 객체 생성
        enter -> server : [Request] 차량 등록
        note right : vehicle_id, enter_date
        activate server #yellow
            server -> server : [Query-Create] 차량 저장
                main -> main : 차량 객체 생성
                activate main
                    main -> server : [Request] 차량 객체 등록
                    note right : obj_id
                    server -> server : [Query-Update] 차량 객체 연결
                    server -> main : [Response] 차량 id 반환
                    main -> main : 차량 객체 id 연결
                deactivate main
            server -> server : [Query-Select] 빈 자리 조회
            server -> server : 경로 설정
            server -> enter : [Response] 경로 반환
            note right : 모니터에 주차위치, 차량 번호, 입차시간 표시
        deactivate server
deactivate enter
end

==경로 안내==
group 교차로 신호
main -> main : 차량 교차로 진입
activate main
    main -> server : [Request] 교차로 신호 조회
    note right : vehicle_id, junction_id
deactivate main
activate server #yellow
    server -> server : [Query-select] 차량 경로 조회
    server -> sign : [Request] 교차로 신호 전달
    activate sign
        sign -> sign : 신호등 동작
        sign -> server : [Response] success
    deactivate sign
deactivate server
end

group 경로 변경
main -> main : 경로 이탈 차량 감지
activate main
    main -> server : [Request] 경로이탈 차량, 경로 위치 전달
    note right : vehicle_id, route_id
    activate server #yellow
        server -> server : [Query-select] 해당경로 이용 차량 조회
        alt 차량이 있는 경우
            server -> server : 해당 차량 경로 재설정
            server -> main : [Request] 경로 변경 차량, 변경된 경로 전달
                activate main #red
                main -> main : 해당 차량 경로 변경
                main -> server : [Response] success
                deactivate main
        end
        server -> server : 이탈차량 경로 재설정
        server -> main : [Response] 이탈 차량, 변경된 경로 전달
    deactivate server
deactivate main
end

group 출차 차량 경로 방해
main -> main : 차량 경로에 출차차량 감지
activate main
    main -> server : [Request] 경로 위치 전달
    activate server #yellow
        server -> server : [Query-select] 해당경로 이용 차량 조회
        alt 차량이 있는 경우
           server -> server : 해당 차량 경로 재설정
           server -> main : [Request] 경로 변경 차량, 변경된 경로 전달
               activate main #red
               main -> main : 해당 차량 경로 변경
               main -> server : [Response] success
               deactivate main
        end
    server -> main : [Response] success
    deactivate server
deactivate main
end

==주차 조회==
user -> user : 모바일 페이지 접속
activate user
    user -> server : [Request] 차량 번호 조회
    note left : vehicle_id
    activate server #yellow
        server -> server : [Query-Select] 차량 정보 조회
        server -> user : [Response] 차량 정보 반환
        note right : vehicle_id, enter_date, \n parking_time, charge
    deactivate server
deactivate user
==출차 관리==
EntranceCam -> server : [Request] 차량 정보 조회
activate enter
note right : 총 주차시간, 주차요금
activate server #yellow
    server -> server : [Query-Select] 주차 요금 조회
    server -> enter : [Response] 주차 요금 정보 반환
deactivate server
enter -> user : 주차 요금 알림
activate user
user -> enter : 결제
deactivate user
deactivate enter

deactivate main
@enduml