@startuml
title Smart-Parking-Lot
footer Page %page% of %lastpage%

actor USER as user
actor Administrator as admin
control Server as server
entity MainCam as main
entity EntranceCam as enter

==입차 관리==
enter -> enter : [START] 차량 인식
activate enter
    group 차량 객체 생성
        enter -> server : [Request] 차량 등록
        note right : vehicle_id, enter_date
        activate server #yellow
            server -> server : [Query-Create] 차량 저장
                main -> main : 차량 객체 생성
                activate main
                    main -> server : [Request] 차량 객체 등록
                    note right : obj_id
                    server -> server : [Query-Update] 차량 객체 연결
                    server -> main : [Response] 차량 id 반환
                    main -> main : 차량 객체 id 연결
                deactivate main
            server -> server : [Query-Select] 빈 자리 조회
            server -> server : 경로 설정
            server -> enter : [Response] 경로 반환
            note right : 모니터에 주차위치, 차량 번호, 입차시간 표시
        deactivate server
deactivate enter
end

==경로 안내==

==주차 조회==

==출차 관리==

@enduml